# ASTF-net training configuration

# Dataset and dataloader
data_path: "downloads/"
train_hdf5_file: "${data_path}/Test_level1_pairs_2_Samezero_501_new_3_1.h5"
val_hdf5_file: "${data_path}/Test_level1_pairs_2_Samezero_501_new_3_1.h5"
test_hdf5_file: "${data_path}/Test_level1_pairs_2_Samezero_501_new_3_1.h5"
batch_size: 32
num_workers: 4

# Data augmentations (SpeechBrain style)
data_augmentations:
  - AddRandomNoise:
      noise_level: 0.5
  - DropRegion:
      max_drop_length: 10
  - AddTrend:
      min_deg: -2
      max_deg: 2

# Model hyperparameters
in_channels: 2
output_length: 501
lr: 0.001
max_epochs: 2

# Optimization
loss: "nonzero_weighted_mse"

output_dir: "output/"
