name: CI
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: python-3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.4
    - name: linting checks
      run: |
        uv sync --all-extras
        uv run ruff check .
    - name: install project dependencies
      run: |
        uv run pip install -e .
    - name: unit tests
      run: |
        pytest --cov=astfnet
    - name: type checking
      run: |
        pytype astfnet/
    - name: doc-creation-test
      run: |
        ./tests/test_docs/run.sh
